### ISSUE TITLE
Error when trying to use vscode generator with yo 4.0.0

### ISSUE THREAD

**Issue by Inch4Tk** [yeoman/yo#661]
## Type of issue
I wanted to create a new vscode extension with the new yo version. Everything works fine with 3.1.1, but I get an error with 4.0.0. See attached cli output.

----

## My environment

* *OS version/details*: `Windows 10 64-bit`
* *Node version:* `10.17.0`
* *npm version:* `7.10.0`
* *Version of yo :* `4.0.0`

## Expected behavior

I will be prompted with the vscode package generation questionnaire.

## Current behavior

I get a cli error.

## Steps to reproduce the behavior
```
npm install -g yo generator code
yo code
```
## Command line output

```
C:\Users\inch\AppData\Roaming\nvm\v10.17.0\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:70
    filePatterns: lookups.flatMap(prefix => [`${prefix}/*/index.ts`, `${prefix}/*/index.js`]),
                          ^

TypeError: lookups.flatMap is not a function
    at Environment.resolver.lookup (C:\Users\inch\AppData\Roaming\nvm\v10.17.0\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:70:27)
    at init (C:\Users\inch\AppData\Roaming\nvm\v10.17.0\node_modules\yo\lib\cli.js:130:7)
    at pre (C:\Users\inch\AppData\Roaming\nvm\v10.17.0\node_modules\yo\lib\cli.js:89:3)
    at Object.<anonymous> (C:\Users\inch\AppData\Roaming\nvm\v10.17.0\node_modules\yo\lib\cli.js:219:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Comment by mshima** [comment]
yo@4 requires node >= 12.10.0

**Comment by Inch4Tk** [comment]
Ok, that works. Thanks!
